[package]
name = "ini-as-rest"
version = "0.1.0"
edition = "2021"


[dependencies]
rust-ini = "0.18.0"
serde = "1.0.137"
dirs ="4.0.0"

[dependencies.clap]
version = "3.1.18"
features = ["derive"]

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]
